# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'


target 'Surf_Advisor_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Surf_Advisor_iOS

  target 'Surf_Advisor_iOSTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Kingfisher'
pod 'Alamofire'
pod 'SwiftyJSON'
  end

end
